spring:
  application:
    name: api_catalogo

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/catalogo_db}
    username: ${SPRING_DATASOURCE_USERNAME:catalogo_user}
    password: ${SPRING_DATASOURCE_PASSWORD:catalogo_pass}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8081